sudo: false
language: php
cache:
  directories:
  - "$HOME/.composer/cache"
  - vendor
matrix:
  fast_finish: true
  include:
  - php: 7.1
    env:
    - EXECUTE_DEPLOYMENT=true
before_install:
- openssl aes-256-cbc -K $encrypted_097b85c62af8_key -iv $encrypted_097b85c62af8_iv
  -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
- phpenv config-rm xdebug.ini
- composer self-update
install:
- travis_retry composer install --no-interaction
- composer info -i
notifications:
  email: true
after_success:
- if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then composer install --no-dev ; fi
- if [[ $EXECUTE_DEPLOYMENT == 'true' && $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then ./bin/deploy.sh ; fi
